"""Curated airport-location learning bank.

Coordinates refer to the supplied 566 x 739 locations_blank.png chart.  Each point
marks the destination of the matching coloured callout on the blank location chart;
learners click the marker/feature, not the empty callout box.
"""

from __future__ import annotations

LOCATIONS_CANVAS_WIDTH = 566
LOCATIONS_CANVAS_HEIGHT = 739

LOCATION_QUESTION_BANK = [
    # Navigation and weather equipment
    {
        "id": "loc_rwy_35r",
        "label": "LOC RWY 35R",
        "category": "Navigation aid",
        "clue": "The blue localizer marker at the north end of the eastern runway.",
        "paths": [[[446, 56]]],
        "tolerance": 18,
    },
    {
        "id": "gp_rwy_17l",
        "label": "GP RWY 17L",
        "category": "Navigation aid",
        "clue": "The blue glideslope marker on the eastern runway's north approach.",
        "paths": [[[446, 94]]],
        "tolerance": 18,
    },
    {
        "id": "north_anemometer",
        "label": "North Anemometer",
        "category": "Weather",
        "clue": "The wind-measuring station north-west of the eastern runway complex.",
        "paths": [[[394, 144]]],
        "tolerance": 18,
    },
    {
        "id": "loc_rwy_35l",
        "label": "LOC RWY 35L",
        "category": "Navigation aid",
        "clue": "The blue localizer marker in the upper central field.",
        "paths": [[[223, 254]]],
        "tolerance": 18,
    },
    {
        "id": "gp_rwy_17r",
        "label": "GP RWY 17R",
        "category": "Navigation aid",
        "clue": "The blue glideslope marker immediately south-east of the upper central localizer.",
        "paths": [[[233, 274]]],
        "tolerance": 18,
    },
    {
        "id": "loc_rwy_26",
        "label": "LOC RWY 26",
        "category": "Navigation aid",
        "clue": "The western blue localizer marker beside the diagonal runway.",
        "paths": [[[132, 305]]],
        "tolerance": 19,
    },
    {
        "id": "gp_rwy_11",
        "label": "GP RWY 11",
        "category": "Navigation aid",
        "clue": "The western blue glideslope marker below the localizer at the diagonal runway.",
        "paths": [[[106, 310]]],
        "tolerance": 19,
    },
    {
        "id": "gp_rwy_29",
        "label": "GP RWY 29",
        "category": "Navigation aid",
        "clue": "The blue glideslope marker near the centre of the diagonal-runway exit.",
        "paths": [[[306, 431]]],
        "tolerance": 18,
    },
    {
        "id": "loc_rwy_11",
        "label": "LOC RWY 11",
        "category": "Navigation aid",
        "clue": "The blue localizer marker just east of the diagonal-runway glideslope marker.",
        "paths": [[[334, 434]]],
        "tolerance": 18,
    },
    {
        "id": "gp_rwy_35l",
        "label": "GP RWY 35L",
        "category": "Navigation aid",
        "clue": "The blue marker on the lower central runway approach.",
        "paths": [[[233, 620]]],
        "tolerance": 18,
    },
    {
        "id": "loc_rwy_17r",
        "label": "LOC RWY 17R",
        "category": "Navigation aid",
        "clue": "The blue localizer marker at the lower end of the central runway.",
        "paths": [[[222, 644]]],
        "tolerance": 18,
    },
    {
        "id": "gp_rwy_35r",
        "label": "GP RWY 35R",
        "category": "Navigation aid",
        "clue": "The blue glideslope marker beside the east runway's lower approach.",
        "paths": [[[446, 470]]],
        "tolerance": 18,
    },
    {
        "id": "loc_rwy_17l",
        "label": "LOC RWY 17L",
        "category": "Navigation aid",
        "clue": "The blue localizer marker at the lower end of the eastern runway.",
        "paths": [[[434, 494]]],
        "tolerance": 18,
    },
    {
        "id": "south_anemometer",
        "label": "South Anemometer",
        "category": "Weather",
        "clue": "The wind-measuring station west of the south apron.",
        "paths": [[[168, 646]]],
        "tolerance": 20,
    },

    # Facilities and operational locations
    {
        "id": "west_deice",
        "label": "West De-Ice",
        "category": "Facility",
        "clue": "The orange de-icing position west of the terminal complex.",
        "paths": [[[306, 295]]],
        "tolerance": 23,
    },
    {
        "id": "east_deice",
        "label": "East De-Ice",
        "category": "Facility",
        "clue": "The orange de-icing position east of the terminal complex.",
        "paths": [[[420, 295]]],
        "tolerance": 23,
    },
    {
        "id": "air_canada_hangar_11",
        "label": "Air Canada Hangar 11",
        "category": "Facility",
        "clue": "The orange hangar marker just south of the central terminal area.",
        "paths": [[[325, 340]]],
        "tolerance": 22,
    },
    {
        "id": "nyc_station_1",
        "label": "NYC Station 1",
        "category": "Operations",
        "clue": "The orange station marker in the central operations area.",
        "paths": [[[306, 355]]],
        "tolerance": 22,
    },
    {
        "id": "control_tower",
        "label": "Control Tower",
        "category": "Operations",
        "clue": "The prominent orange circular marker near the central terminal.",
        "paths": [[[345, 350]]],
        "tolerance": 22,
    },
    {
        "id": "westjet_hangar",
        "label": "WestJet Hangar",
        "category": "Facility",
        "clue": "The orange hangar marker south-east of the control tower.",
        "paths": [[[365, 378]]],
        "tolerance": 22,
    },
    {
        "id": "fec",
        "label": "FEC",
        "category": "Facility",
        "clue": "The orange facility marker on the lower west side of the terminal field.",
        "paths": [[[319, 451]]],
        "tolerance": 22,
    },
    {
        "id": "east_fec",
        "label": "East FEC",
        "category": "Facility",
        "clue": "The orange facility marker east of the central diagonal runway crossing.",
        "paths": [[[398, 416]]],
        "tolerance": 22,
    },
    {
        "id": "central_compass_rose",
        "label": "Central Compass Rose",
        "category": "Reference point",
        "clue": "The orange compass-rose reference point south of the central terminal.",
        "paths": [[[346, 480]]],
        "tolerance": 22,
    },
    {
        "id": "bomb_threat_area",
        "label": "Bomb Threat Area",
        "category": "Safety",
        "clue": "The first orange safety-area marker in the lower central chain.",
        "paths": [[[346, 494]]],
        "tolerance": 22,
    },
    {
        "id": "aircraft_graveyard",
        "label": "Aircraft Graveyard",
        "category": "Operations",
        "clue": "The orange marker directly below the bomb-threat-area marker.",
        "paths": [[[348, 506]]],
        "tolerance": 22,
    },
    {
        "id": "bomb_disposal_area",
        "label": "Bomb Disposal Area",
        "category": "Safety",
        "clue": "The orange safety-area marker below the aircraft graveyard.",
        "paths": [[[349, 518]]],
        "tolerance": 22,
    },
    {
        "id": "crash_mockup_site",
        "label": "Crash Mock-Up Site",
        "category": "Safety",
        "clue": "The final orange marker in the lower central safety chain.",
        "paths": [[[351, 530]]],
        "tolerance": 22,
    },
    {
        "id": "response_gate_west",
        "label": "Response Gate West",
        "category": "Operations",
        "clue": "The west-side orange response-gate marker.",
        "paths": [[[184, 522]]],
        "tolerance": 22,
    },
    {
        "id": "airside_maintenance_centre",
        "label": "Airside Maintenance Centre",
        "category": "Facility",
        "clue": "The orange maintenance-centre marker on the lower west side.",
        "paths": [[[224, 560]]],
        "tolerance": 22,
    },
    {
        "id": "huack_area",
        "label": "HUACK Area",
        "category": "Facility",
        "clue": "The orange marker above the south apron and terminal complex.",
        "paths": [[[319, 584]]],
        "tolerance": 22,
    },
    {
        "id": "technical_area_lima_east",
        "label": "Technical Area Lima East",
        "category": "Facility",
        "clue": "The orange technical-area marker east of the south apron.",
        "paths": [[[384, 565]]],
        "tolerance": 22,
    },
]

LOCATIONS_BY_ID = {question["id"]: question for question in LOCATION_QUESTION_BANK}
